apiVersion: v1
kind: Service
metadata:
  name: brokerage
  labels:
    app: brokerage
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: brokerage
  type: ClusterIP
